/*
 ***************************************************************************************************
 * Storm -  Smart Telemetry & Operational Recording for Mindstorm https://github.com/ToCap/Storm
 *
 * Copyright (C) 2025  GC-MS Software (ThomTheCat)
 *
 * This source code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation; See <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>.
 *
 *  Software distributed under the License is distributed on an "AS IS"
 *  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 *  License for the specific language governing rights and limitations
 *  under the License.
 ***************************************************************************************************
*/


edition = "2023";

package mindstorm;

enum TouchSensorModes
{
	MEASURE = 0;
	COMPARE = 1;
}


enum TouchSensorStates
{
	RELEASED = 0;
	PRESSED = 1;
	BUMPED = 2;
}

message TouchSensorData {
	uint64 timestamp = 1;
	TouchSensorModes mode = 2;

	oneof payload {
		MeasureData		measure      = 3;
		CompareData		compare       = 4;
  }
}

message MeasureData {
  bool state = 1; // rue if the touch sensor is pressed, False if not.
}

message CompareData {
  bool result = 1;
  TouchSensorStates measure = 2;
}
