# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrared_sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infrared_sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15infrared_sensor.proto\x12\tmindstorm\"\xe7\x01\n\x12InfraredSensorData\x12,\n\x04mode\x18\x01 \x01(\x0e\x32\x1e.mindstorm.InfraredSensorModes\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12-\n\tproximity\x18\x03 \x01(\x0b\x32\x18.mindstorm.ProximityDataH\x00\x12+\n\x08\x64\x65tected\x18\x04 \x01(\x0b\x32\x17.mindstorm.DetectedDataH\x00\x12)\n\x07heading\x18\x05 \x01(\x0b\x32\x16.mindstorm.HeadingDataH\x00\x42\t\n\x07payload\"\x1e\n\rProximityData\x12\r\n\x05value\x18\x01 \x01(\r\"\x1d\n\x0c\x44\x65tectedData\x12\r\n\x05state\x18\x01 \x01(\x08\"\x1e\n\x0bHeadingData\x12\x0f\n\x07heading\x18\x01 \x01(\x11*?\n\x13InfraredSensorModes\x12\r\n\tPROXIMITY\x10\x00\x12\x0c\n\x08\x44\x45TECTED\x10\x01\x12\x0b\n\x07HEADING\x10\x02\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrared_sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFRAREDSENSORMODES']._serialized_start=365
  _globals['_INFRAREDSENSORMODES']._serialized_end=428
  _globals['_INFRAREDSENSORDATA']._serialized_start=37
  _globals['_INFRAREDSENSORDATA']._serialized_end=268
  _globals['_PROXIMITYDATA']._serialized_start=270
  _globals['_PROXIMITYDATA']._serialized_end=300
  _globals['_DETECTEDDATA']._serialized_start=302
  _globals['_DETECTEDDATA']._serialized_end=331
  _globals['_HEADINGDATA']._serialized_start=333
  _globals['_HEADINGDATA']._serialized_end=363
# @@protoc_insertion_point(module_scope)
