# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: touch_sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'touch_sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12touch_sensor.proto\x12\tmindstorm\"\xb0\x01\n\x0fTouchSensorData\x12)\n\x04mode\x18\x01 \x01(\x0e\x32\x1b.mindstorm.TouchSensorModes\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12)\n\x07measure\x18\x03 \x01(\x0b\x32\x16.mindstorm.MeasureDataH\x00\x12)\n\x07\x63ompare\x18\x04 \x01(\x0b\x32\x16.mindstorm.CompareDataH\x00\x42\t\n\x07payload\"\x1c\n\x0bMeasureData\x12\r\n\x05state\x18\x01 \x01(\x08\"L\n\x0b\x43ompareData\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12-\n\x07measure\x18\x02 \x01(\x0e\x32\x1c.mindstorm.TouchSensorStates*,\n\x10TouchSensorModes\x12\x0b\n\x07MEASURE\x10\x00\x12\x0b\n\x07\x43OMPARE\x10\x01*:\n\x11TouchSensorStates\x12\x0c\n\x08RELEASED\x10\x00\x12\x0b\n\x07PRESSED\x10\x01\x12\n\n\x06\x42UMPED\x10\x02\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'touch_sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOUCHSENSORMODES']._serialized_start=320
  _globals['_TOUCHSENSORMODES']._serialized_end=364
  _globals['_TOUCHSENSORSTATES']._serialized_start=366
  _globals['_TOUCHSENSORSTATES']._serialized_end=424
  _globals['_TOUCHSENSORDATA']._serialized_start=34
  _globals['_TOUCHSENSORDATA']._serialized_end=210
  _globals['_MEASUREDATA']._serialized_start=212
  _globals['_MEASUREDATA']._serialized_end=240
  _globals['_COMPAREDATA']._serialized_start=242
  _globals['_COMPAREDATA']._serialized_end=318
# @@protoc_insertion_point(module_scope)
